name: Main

on:
  - push
  - pull_request

permissions:
  contents: read

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: ['3.2', '3.3', '3.4']
        channel: ['stable']
        include:
          - ruby: 'head'
            channel: 'experimental'

    continue-on-error: ${{ matrix.channel != 'stable' }}

    steps:
      - uses: actions/checkout@v4

      # Setup ruby dependencies
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      # Setup node dependencies
      - uses: pnpm/action-setup@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'
      - name: Install node dependencies
        run: pnpm install

      # Actually run tests and lint
      - name: Lint and test
        run: |
          bundle exec rubocop
          pnpm lint
          pnpm print --check '**/*'
          pnpm test

  automerge:
    name: AutoMerge
    needs: ci
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.actor == 'dependabot[bot]'
    steps:
    - uses: actions/github-script@v3
      with:
        script: |
          github.pulls.merge({
            owner: context.payload.repository.owner.login,
            repo: context.payload.repository.name,
            pull_number: context.payload.pull_request.number
          })
